---
- name: Check if GitKraken is installed
  command: dpkg-query -W {{gitkraken_deb_filename}}
  register: deb_check
  failed_when: deb_check.rc > 1
  changed_when: deb_check.rc == 1  

- name: Download GitKraken
  get_url:
    url="https://release.gitkraken.com/linux/{{gitkraken_deb_filename}}"
    dest="/home/{{username}}/Downloads/{{gitkraken_deb_filename}}"
  when: deb_check.rc == 1

- name: Install GitKraken
  apt: deb="/home/{{username}}/Downloads/{{gitkraken_deb_filename}}"
  sudo: true
  when: deb_check.rc == 1  

