---
- name: Playbook for basic linux environment
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  become_method: sudo
  roles:
    - basic    
    - { role: nvidia, tags: ['nvidia']}
    - { role: gnome-basics, tags: ['gnome', 'elementaryOS']}
    - { role: elementary-os, tags: ['elementaryOS']}
  

- name: Playbook for common tools
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  become_method: sudo
  roles:    
    - { role: firefox, tags: ['browsers']}
    - { role: chrome, tags: ['browsers']}    
    #- { role: vivaldi, tags: ['browsers']}        
    - office
    - send-anywhere

  - name: Playbook for IMs
    hosts: localhost
    connection: local
    gather_facts: yes
    become: yes
    become_method: sudo
    tags:
      - im
    roles:    
      - { role: telegram, tags: ['im', 'telegram']}
      - { role: slack, tags: ['im', slack]}          

- name: Playbook for development environments
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  become_method: sudo
  tags: 
    - dev
  roles:        
    - sublime-text
    - development
    - { role: gitkraken, tags: ['dev', 'git', 'gitkraken']}    


- name: Playbook for Nokia environment
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
    - { role: pidgin, tags: ['nokia']}
    - { role: nokia-networking, tags: ['nokia']}

    