---
- name: Playbook for basic linux environment
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  become_method: sudo
  roles:
    - basic    
    - { role: bash-profile, tags: ['bash']}
    - { role: nvidia, tags: ['nvidia'], when: ansible_product_version when == 'ThinkPad T420'}
    - { role: gnome-basics, tags: ['gnome']}
    - { role: elementary-os, tags: ['elementaryOS'], when: ansible_distribution == 'elementary'}
  

- name: Playbook for common tools
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  become_method: sudo
  roles:    
    - { role: firefox, tags: ['browsers']}
    - { role: chrome, tags: ['browsers']}    
    #- { role: vivaldi, tags: ['browsers']}        
    - office
    - send-anywhere
    - { role: productivity, tags: ['productivity']}

- name: Playbook for IMs
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  become_method: sudo
  tags:
    - im
  roles:    
    - { role: telegram, tags: ['im', 'telegram']}
    - { role: slack, tags: ['im', slack]}

- name: Playbook for development environments
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  become_method: sudo
  tags: 
    - dev
  roles:        
    - sublime-text
    - { role: git, tags: ['git']}
    - { role: dev-java, tags: ['dev-java']}
    - { role: dev-python, tags: ['dev-python']}
    - { role: dev-nodejs, tags: ['dev-nodejs']}
    - { role: gitkraken, tags: ['git', 'gitkraken']}
    - { role: sbt, tags: ['build', 'sbt', 'playframework']}


- name: Playbook for Nokia environment
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
    - { role: pidgin, tags: ['nokia']}
    - { role: nokia-networking, tags: ['nokia']}

    
