---
# SublimeText 3

- name: Does the Sublime Text apt file exist?
  command: test -f {{sublimetext_apt_file}}
  register: sublime_apt_exists
  ignore_errors: True
  tags:
    - sublime-text

- name: Add Sublime key
  shell: wget -q -O - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
  when: sublime_apt_exists.rc == 1
  tags:
    - sublime-text

- name: Ensure apt is set up to work with https sources
  apt: pkg=apt-transport-https state=installed
  tags:
    - sublime-text

- name: Add channel to sources list
  shell: echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
  when: sublime_apt_exists.rc == 1
  tags:
    - sublime-text

- name: Update apt cache
  apt: update_cache=yes
  when: sublime_apt_exists.rc == 1
  tags:
    - sublime-text

- name: Install Sublime Text
  apt: pkg=sublime-text state=installed
  tags:
    - sublime-text

- name: Install Sublimetext plugins
  tags:
    - sublime-text
  vars:
    packagecontrol_dir_bin: "{{sublimetext_packagecontrol_dir_bin}}"
    packagecontrol_packages: "{{sublimetext_packagecontrol_packages}}"
  include_role:
    name: igor_mukhin.sublimetext3_packagecontrol
      
