---
- name: Update package list
  apt: update_cache=yes cache_valid_time=86400

- name: Add PPA repo for Elementary Tweaks
  apt_repository: repo='ppa:philip.scott/elementary-tweaks'
- name: Install Elementary Tweaks
  apt: name=elementary-tweaks state=latest

- name: Remove unnecessary applications
  apt: name={{item}} state=absent
  with_items:
    - midori-granite
    - pantheon-files
    - scratch-text-editor
    - epiphany
    - epiphany-browser
  ignore_errors: True

- name: Disable Guest account
  lineinfile:
    dest: /usr/share/lightdm/lightdm.conf.d/40-pantheon-greeter.conf
    regexp: '^allow-guest='
    line: 'allow-guest=false'

- name: Configure workspaces
  gsetting: key={{item[0]}}
            value={{item[1]}}
  with_items:
    - ['org.gnome.mutter.dynamic-workspaces','true']
    - ['org.gnome.mutter.workspaces-only-on-primary', 'true']

# Indicators

- name: Check if indicator-workspaces_0.5_all is installed
  command: dpkg-query -W indicator-workspaces_0.5_all
  register: indicator_check_deb
  failed_when: indicator_check_deb.rc > 1
  changed_when: indicator_check_deb.rc == 1

- name: Download indicator-workspaces_0.5_all.deb
  get_url:
    url="https://github.com/dyson/indicator-workspaces/releases/download/v0.5/indicator-workspaces_0.5_all.deb"
    dest="/home/{{username}}/Downloads/indicator-workspaces_0.5_all.deb"
  when: indicator_check_deb.rc == 1

- name: Install indicator-workspaces_0.5_all
  apt: deb="/home/{{username}}/Downloads/indicator-workspaces_0.5_all.deb"
  when: indicator_check_deb.rc == 1

- name: Install Indicators
  apt: name={{item}} state=latest
  with_items:
    - indicator-cpufreq
    - indicator-multiload

- name: Configure Workspaces Indicator
  gsetting: key={{item[0]}}
            value={{item[1]}}
  with_items:
    - ['apps.indicator-workspaces.show-label', 'false']

- name: Configure Multiload Indicator
  gsetting: key={{item[0]}}
            value={{item[1]}}
  with_items:
    - ['de.mh21.indicator.multiload.general.autostart', 'true']
    - ['de.mh21.indicator.multiload.graphs.cpu.enabled', 'true']
    - ['de.mh21.indicator.multiload.graphs.disk.enabled', 'true']
    - ['de.mh21.indicator.multiload.graphs.mem.enabled', 'true']
    - ['de.mh21.indicator.multiload.graphs.swap.enabled', 'true']
    - ['de.mh21.indicator.multiload.general.system-monitor', 'gnome-system-monitor']

- name: Configure Ubuntu
  gsetting: key={{item[0]}}
            value={{item[1]}}
  with_items:
    - ['com.ubuntu.update-notifier.show-apport-cashes', 'false']

- name: Configure Appearance
  gsetting: key={{item[0]}}
            value={{item[1]}}
  with_items:
    - ['org.pantheon.desktop.gala.appearance.alt-tab-window-opacity', '0.3']
    - ['org.pantheon.desktop.gala.appearance.button-layout', 'close:minimize,maximize']    
    - ['org.pantheon.desktop.gala.behavior.dynamic-workspaces', 'true']
    - ['org.pantheon.desktop.gala.behavior.hotcorner-topleft', 'window-overview-all']
    - ['org.pantheon.desktop.gala.behavior.hotcorner-topright', 'show-workspace-view']    
    - ['org.pantheon.desktop.slingshot.columns', 2]
    - ['org.pantheon.desktop.slingshot.rows', 2]
    - ['org.pantheon.desktop.wingpanel.indicators.bluetooth.bluetooth-enabled', 'true']
    - ['org.pantheon.desktop.wingpanel.indicators.datetime.show-weeks', 'true']
    - ['org.pantheon.desktop.wingpanel.indicators.power.show-percentage', 'true']


- name: Configure Plank
  gsetting: key={{item[0]}}
            value={{item[1]}}
  with_items:
    - ['net.launchpad.plank.docks.dock1.position', 'left']
    - ['net.launchpad.plank.docks.dock1.theme', 'Transparent']
    - ['org.pantheon.files.preferences.date-format', 'iso']
    - ['org.pantheon.files.preferences.default-viewmode', 'list']
    - ['org.pantheon.files.preferences.restore-tabs', 'true']
    - ['org.pantheon.files.preferences.single-click', 'false']
    - ['org.gtk.Settings.FileChooser.sort-directories-first', 'true']

- name: Configure Shotwell
  gsetting: key={{item[0]}}
            value={{item[1]}}
  with_items:
    - ['org.pantheon.photos.preferences.editing.external-photo-editor', 'gimp']
    - ['org.pantheon.photos.preferences.editing.external-raw-editor', 'rawtherapee']

- name: Configure Key bindings
  gsetting: key={{item[0]}}
            value={{item[1]}}
  with_items:
    - ['org.gnome.desktop.wm.keybindings.begin-move', '[]']
    - ['org.gnome.desktop.wm.keybindings.begin-resize', '[]']
    - ['org.gnome.desktop.wm.keybindings.cycle-group', '[]']
    - ['org.gnome.desktop.wm.keybindings.cycle-windows', '[]']
    - ['org.gnome.desktop.wm.keybindings.cycle-panels', '[]']
    - ['org.gnome.desktop.peripherals.touchpad.natural-scroll', 'false']
