---
- name: Does the Google apt file exist?
  command: test -f {{chrome_apt_file}}
  register: google_apt_exists
  ignore_errors: True
  tags:
    - chrome

- name: Add Google Chrome key
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: google_apt_exists.rc == 1
  tags:
    - chrome

- name: Add Google Chrome repo
  copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{chrome_apt_file}} owner=root group=root mode=644
  when: google_apt_exists.rc == 1
  tags:
    - chrome

- name: Update apt cache
  apt: update_cache=yes
  when: google_apt_exists.rc == 1
  tags:
    - chrome

- name: Install Google Chrome
  apt: pkg=google-chrome-stable state=installed
  tags:
    - chrome

  #todo "Download Freya Theme for Chrome: https://chrome.google.com/webstore/detail/freya-theme-for-google-ch/nofpaaefcomkhdkeihhnonlmhajfadgd"
  #todo "Download Scrollbars for Chrome: https://chrome.google.com/webstore/detail/elementary-freya-scrollba/dddhhloahgkhcaipmkfjngdalegmcomm"